# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swacch', '0005_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
